#!/bin/bash
#cp /home/pi/photobooth_images/*.jpg /home/pi/PB_Originals
mogrify -resize 1500x1000 /home/pi/photobooth_images/*.jpg
montage /home/pi/photobooth_images/*.jpg -tile 1x4 -geometry +1+1 /home/pi/temp_montage2.jpg
montage /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg -tile 1x2 -geometry +1+1 /home/pi/temp_montage3.jpg
montage /home/pi/temp_montage3.jpg /home/pi/temp_montage3.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage4.jpg
suffix=$(date +%Y%m%d%H%M%S)
cp /home/pi/temp_montage4.jpg /home/pi/PB_archive/PB_${suffix}.jpg
#rm /home/pi/photobooth_images/*.jpg
#rm /home/pi/temp*
