#!/usr/bin/python

import time, os, subprocess, sys

while True:
  if (1):
    snap = 0
    while snap <4:
      print("pose!")
      snap += 1
      time.sleep(.1)
      print("SNAP=%d" %snap)
      gpout = subprocess.check_output("gphoto2 --capture-image-and-download --filename /home/pi/photobooth_images/photobooth%Y%m%d%H%M%S.jpg", stderr=subprocess.STDOUT, shell=True)
      print(gpout)
      
      time.sleep(0.1)
    print("please wait while your photos print...")

    subprocess.call("sudo /home/pi/scripts/photobooth_tester/assemble_and_print", shell=True)
    time.sleep(10)
    print("ready for next round")
    sys.exit("End of Test")
    

